server:
  port: 9002
  servlet:
    context-path: /sleuth-cart
spring:
  application:
    name: sleuth-cart
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-path: ${server.servlet.context-path}/actuator/health
        prefer-ip-address: true
  zipkin:
    #sender.type=web时需要
#    base-url: http://localhost:9411/
    service:
      name: ${spring.application.name}
    sender:
      type: kafka
  kafka:
    bootstrap-servers: 10.1.31.60:9092
  sleuth:
    sampler:
      #设置采样率，默认为0.1，设置太高可能会影响性能；这里设置为1仅推荐测试使用
      probability: 1