server:
  port: 9001
spring:
  application:
    name: sleuth-search
  cloud:
    consul:
      discovery:
        register: false
      host: localhost
      port: 8500
  zipkin:
    base-url: http://localhost:9411/
    service:
      name: sleuth-search
    sender:
      type: web
  sleuth:
    sampler:
      #设置采样率，默认为0.1，设置太高可能会影响性能；这里设置为1仅推荐测试使用
      probability: 1