server:
  port: 9001
spring:
  application:
    name: sleuth-search
  cloud:
    consul:
      discovery:
        register: false
      host: localhost
      port: 8500
  zipkin:
    #sender.type=web时需要
#    base-url: http://localhost:9411/
    service:
      name: ${spring.application.name}
    sender:
      type: kafka
  kafka:
    bootstrap-servers: 10.1.31.60:9092
  sleuth:
    sampler:
      #设置采样率，默认为0.1，设置太高可能会影响性能；这里设置为1仅推荐测试使用
      probability: 1