server:
  port: 8001
spring:
  application:
    name: sentinel-datasource-nacos
  cloud:
    sentinel:
      transport:
        ## Sentinel 控制台地址
        dashboard: localhost:8080
        ## 与控制台通信的客户端端口
        port: 8700
        ## 应用与Sentinel控制台的心跳间隔时间
        heartbeat-interval-ms: 30000
      datasource:
        flow:
          nacos:
            server-addr: localhost:8848
            ## nacos配置中心dataId。在整合nacos做动态规则源时与Sentinel Dashboard中flowRuleNacosProvider中配置的dataId要一致。
            dataId: ${spring.application.name}-flow-rules
            data-type: json
            # 规则类型，取值见：
            # com.alibaba.cloud.sentinel.datasource.RuleType
            rule-type: flow #流控规则
            groupId: SENTINEL_GROUP
        degrade:
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}-degrade-rules
            data-type: json
            rule-type: degrade  #降级规则
            groupId: SENTINEL_GROUP
        system:
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}-system-rules
            data-type: json
            rule-type: system #系统规则
            groupId: SENTINEL_GROUP
        authority:
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}-authority-rules
            data-type: json
            rule-type: authority  #授权规则
            groupId: SENTINEL_GROUP
        param-flow:
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}-param-flow-rules
            data-type: json
            rule-type: param-flow #热点参数规则
            groupId: SENTINEL_GROUP