server:
  port: 8002
  servlet:
    context-path: /nacos-provider
management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
