server:
  port: 8003
#  servlet:
#    context-path: /nacos-consumer
management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        register-enabled: false
